# Generated by Django 4.0.2 on 2022-02-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_prof_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='prof_book',
        ),
    ]
