# Generated by Django 4.0.2 on 2022-02-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_profile',
        ),
    ]
